package com.android.taxivaxi.operator.app.location;

/**
 * 
 * @author Santosh.Patar This enum is for Handle to WebService Event
 */
public enum EventsToHandle {
	SUCCESS, FAILURE, GP, FB, UPDATEPROFILE, CHANGEPASSWORD, YES, NO, LATLONG_FOUND, PROVIDER_DISABLE, FROMSPLASH, FROMHOME, REMOVEFAVOURITEFROMDETAILS, ADDFAVOURITE, REMOVEFAVOURITES, VIEWFAVOURITES, VIEWBOOKING, CANCELBOOKING, VIEWBOOKINGFROMHOME, FRIENDFAVORITES
	/*
	 * FOODPREFERENCES, RESTAURANTTYPE,CUISINETYPE,BYTAG,HOMERESTAURENTDETAILS,FAVORITESDETAILS,SEARCHRESTAURANTDETAILS,
	 * ,VIEWCART,DELETCARD,VIEWCHECKINGROUP,DELETCHECKINGROUP;
	 */
}
